name: CI
on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Remove .mvn/jvm.config
        if: ${{ matrix.java == 8 }}
      - name: Test
        run: mvn --batch-mode --show-version verify
